version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: safezone-postgis
    environment:
      POSTGRES_DB: safezone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: safezone-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@safezone.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
